buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'de.undercouch:gradle-download-task:4.1.1'
	}
}

plugins {
	id 'java-library'
	id 'maven-publish'
	id 'signing'
}

apply plugin: 'de.undercouch.download'

sourceCompatibility = 1.8
def baseVersion = '3.9.4'
def adempiereRelease = '3.9.3-rs-4.3'
def baseGroupId = 'io.github.adempiere'

repositories {
    mavenLocal()
    mavenCentral()
}

allprojects {
    tasks.withType(Javadoc).all { enabled = false }
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
   api fileTree(
        dir: 'lib',
        include: [
            '*.jar'
        ]
    )
    api fileTree(
        dir: 'dependences',
        include: [
            '*.jar'
        ]
    )
    api files('dependences/classes')
}

sourceSets {
    main {
         java {
            srcDirs = ['src/main/java']
         }
    }
}

java {
    withJavadocJar()
    withSourcesJar()
}


def entityType = 'WHH'
group = "io.github.adempiere"
version = findProperty("deployVersion") ?: "local-1.0.0"

jar {
    manifest {
        attributes("Implementation-Title": "Withholding Engine",
                   "Implementation-Version": version, 
                   "EntityType": entityType)
    }
}

task refreshDependences(){
	file('dependences').mkdirs()
	file('dependences/tmp/').mkdirs()
	file('dependences/webuiClass').mkdirs()
	doLast {
		download {
            src 'http://github.com/erpcya/adempiere/releases/download/' + adempiereRelease + '/Adempiere_393LTS.tar.gz'
            dest 'dependences/tmp/Adempiere_393LTS.tar.gz'
            overwrite false
        }
        
        copy {
            from tarTree(resources.gzip('dependences/tmp/Adempiere_393LTS.tar.gz'))
            into 'dependences/tmp'
        }
        
        copy {
            from zipTree('dependences/tmp/Adempiere/lib/webui.war')
            into 'dependences/webuiClass/'
        }
        
        copy {
        	from "dependences/tmp/Adempiere/lib"
        	into "dependences"
        	include "*.jar"
    	}
    	copy {
        	from fileTree('dependences/tmp/Adempiere/packages/').filter { it.isFile()}
        	into "dependences"
        	include "*.jar"
    	}
    	copy {
        	from "dependences/webuiClass/WEB-INF/lib"
        	into "dependences"
        	include "*.jar"
    	}
    	copy {
	        from "dependences/webuiClass/WEB-INF/classes"
	        into "dependences/classes"
    	}
    	file('dependences/tmp/').deleteDir()
    	file('dependences/webuiClass/').deleteDir()
	}
}

publishing {
    repositories {
		mavenLocal()

        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/erpcya/withholding-engine")
            credentials {
                username = System.properties['deploy.user'] ?: System.getenv("GITHUB_DEPLOY_USER")
                password = System.properties['deploy.token'] ?: System.getenv("GITHUB_DEPLOY_TOKEN")
            }
        }
    }
    publications {
        mavenJava(MavenPublication) {
			groupId = group
			artifactId 'withholding-engine'
			version = version
           	from components.java
           	pom {
                name = 'Withholding Engine'
                description = 'Withholding Engine for ADempiere manage'
                url = 'http://erpya.com/'
                licenses {
                    license {
                        name = 'GNU General Public License v3.0'
                        url = 'https://www.gnu.org/licenses/gpl-3.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'yamelsenih'
                        name = 'Yamel Senih'
                        email = 'ysenih@erpya.com'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/adempiere/withholding-engine.git'
                    developerConnection = 'scm:git:ssh://github.com/adempiere/withholding-engine.git'
                    url = 'http://github.com/adempiere/withholding-engine'
                }
            }
		}
	}
}


task cleanBuildPublishLocal(type: GradleBuild) {
	tasks = ['clean', 'build', 'publishToMavenLocal']
}


signing {
	def isReleaseVersion = !version.toString().startsWith("local") && !version.toString().endsWith("-SNAPSHOT")

	sign configurations.archives

	setRequired {
		(isReleaseVersion || version.toString().equals("build")) && gradle.taskGraph.allTasks.any {
			it.equals(PublishToMavenRepository)
		}
	}
	def signingKey = findProperty("deploySigningKey")
    def signingPassword = findProperty("deploySigningPassword")
    useInMemoryPgpKeys(signingKey, signingPassword)
    sign publishing.publications.mavenJava
}
